import RateCards from "./RateCards";

/**
 * Data list of rates. The comments are generated by ChatGPT.
 */
const rates = [
    {name:"Anna", src: "image/profile1.png", star: 5, content:"I had an amazing dining experience at that restaurant."},
    {name:"Mila", src: "image/profile2.png", star: 4, content:"The restaurant serves the best eggs Benedict I've ever had."},
    {name:"Emily", src: "image/profile3.png", star: 5, content:"The steakhouse lived up to its reputation."},
    {name:"James", src: "image/profile4.png", star: 5, content:"I had the most delicious dessert at the French bakery."},
]

/**
 * The component of Testimonials.
 */
export default function Testimonials() {
    return (
        <section className="bg-pjyellow my-3 py-3 lg:my-10">
            <section className="mx-3 my-5 pt-6 lg:mx-36 lg:my-32">
                <h2 className="font-markazi font-bold text-3xl lg:pb-12">Testimonials</h2>
                <RateCards lst={rates}/>
            </section>
        </section>
    )
}